### ISSUE TITLE
Can I support 32-bit programs by setting?

### ISSUE THREAD

**Issue by Yan-1-20** [trailofbits/sienna-locomotive#391]
I built a 64-bit version and it worked great. But I want to fuzz the 32-bit target. Is there any setting that can be changed?

**Comment by woodruffw** [comment]
Not that the moment, unfortunately 😞. The DR clients and SL server make some assumptions about pointer size, plus the protocol spoken between the clients and the server is mostly ad-hoc and will probably break across different architecture sizes.

I'll close this as a dupe of #319; we'll continue to track interest there.
